import { writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { pathToFileURL } from 'url'


const __dirname = dirname(fileURLToPath(import.meta.url))

// Importar tokens do build
const tokensPath = join(__dirname, '..', 'dist', 'index.mjs')
const tokens = await import(pathToFileURL(tokensPath).href)

function flattenObject(obj, prefix = '') {
  const result = {}
  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}-${key}` : key
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      Object.assign(result, flattenObject(value, newKey))
    } else {
      result[newKey] = value
    }
  }
  return result
}

function toCSSVarName(str) {
  return `--oki-${str.replace(/\./g, '-').replace(/([A-Z])/g, '-$1').toLowerCase()}`
}

function generateCSS() {
  let css = '/* Auto-generated by okiui — do not edit manually */\n\n'
  css += ':root {\n'

  const sections = {
    colors: tokens.colors,
    spacing: tokens.spacing,
    radii: tokens.radii,
    shadows: tokens.shadows,
    motion: tokens.motion,
    breakpoints: tokens.breakpoints,
  }

  // Typography
  const typo = tokens.typography
  for (const [key, value] of Object.entries(typo.fonts)) {
    css += `  --oki-font-${key}: ${value};\n`
  }
  for (const [key, value] of Object.entries(typo.fontSizes)) {
    css += `  --oki-text-${key}: ${value};\n`
  }
  for (const [key, value] of Object.entries(typo.fontWeights)) {
    css += `  --oki-weight-${key}: ${value};\n`
  }
  for (const [key, value] of Object.entries(typo.lineHeights)) {
    css += `  --oki-leading-${key}: ${value};\n`
  }
  css += '\n'

  // Flat sections
  for (const [section, obj] of Object.entries(sections)) {
    const flat = flattenObject(obj, section)
    for (const [key, value] of Object.entries(flat)) {
      if (typeof value === 'string') {
        css += `  ${toCSSVarName(key)}: ${value};\n`
      }
    }
    css += '\n'
  }

  css += '}\n'

  // Dark theme (default)
  css += '\n[data-theme="dark"] {\n'
  const darkFlat = flattenObject(tokens.darkTheme, 'theme')
  for (const [key, value] of Object.entries(darkFlat)) {
    if (typeof value === 'string' && key !== 'theme-name') {
      css += `  ${toCSSVarName(key)}: ${value};\n`
    }
  }
  css += '}\n'

  // Light theme
  css += '\n[data-theme="light"] {\n'
  const lightFlat = flattenObject(tokens.lightTheme, 'theme')
  for (const [key, value] of Object.entries(lightFlat)) {
    if (typeof value === 'string' && key !== 'theme-name') {
      css += `  ${toCSSVarName(key)}: ${value};\n`
    }
  }
  css += '}\n'

  // Write
  const outDir = join(__dirname, '..', 'dist', 'css')
  mkdirSync(outDir, { recursive: true })
  writeFileSync(join(outDir, 'tokens.css'), css)
  console.log('✅ CSS tokens generated')
}

generateCSS()