import { writeFileSync, mkdirSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath, pathToFileURL } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const tokensPath = join(__dirname, '../../tokens/dist/index.mjs')
const tokens = await import(pathToFileURL(tokensPath).href)

function flattenObject(obj, prefix = '') {
  const result = {}
  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}-${key}` : key
    if (typeof value === 'object' && value !== null) {
      Object.assign(result, flattenObject(value, newKey))
    } else {
      result[newKey] = value
    }
  }
  return result
}

function generate() {
  let css = '/* Auto-generated by @okiui/tailwind — do not edit manually */\n\n'
  css += '@theme {\n'

  // Colors
  const flatColors = flattenObject(tokens.colors)
  css += '\n  /* Colors */\n'
  for (const [key, value] of Object.entries(flatColors)) {
    if (typeof value === 'string') {
      css += `  --color-${key}: ${value};\n`
    }
  }

  // Spacing
  css += '\n  /* Spacing */\n'
  for (const [key, value] of Object.entries(tokens.spacing)) {
    css += `  --spacing-${key}: ${value};\n`
  }

  // Typography - font families
  css += '\n  /* Font Families */\n'
  for (const [key, value] of Object.entries(tokens.typography.fonts)) {
    css += `  --font-${key}: ${value};\n`
  }

  // Typography - font sizes
  css += '\n  /* Font Sizes */\n'
  for (const [key, value] of Object.entries(tokens.typography.fontSizes)) {
    css += `  --text-${key}: ${value};\n`
  }

  // Typography - font weights
  css += '\n  /* Font Weights */\n'
  for (const [key, value] of Object.entries(tokens.typography.fontWeights)) {
    css += `  --font-weight-${key}: ${value};\n`
  }

  // Border radius
  css += '\n  /* Border Radius */\n'
  for (const [key, value] of Object.entries(tokens.radii)) {
    css += `  --radius-${key}: ${value};\n`
  }

  // Shadows
  css += '\n  /* Shadows */\n'
  for (const [key, value] of Object.entries(tokens.shadows)) {
    if (typeof value === 'string') {
      css += `  --shadow-${key}: ${value};\n`
    }
  }

  css += '}\n'

  // Dark theme
  css += '\n/* Dark theme (default) */\n'
  css += '[data-theme="dark"] {\n'
  const darkFlat = flattenObject(tokens.darkTheme)
  for (const [key, value] of Object.entries(darkFlat)) {
    if (typeof value === 'string' && key !== 'name') {
      css += `  --color-theme-${key}: ${value};\n`
    }
  }
  css += '}\n'

  // Light theme
  css += '\n/* Light theme */\n'
  css += '[data-theme="light"] {\n'
  const lightFlat = flattenObject(tokens.lightTheme)
  for (const [key, value] of Object.entries(lightFlat)) {
    if (typeof value === 'string' && key !== 'name') {
      css += `  --color-theme-${key}: ${value};\n`
    }
  }
  css += '}\n'

  const outDir = join(__dirname, '..', 'dist')
  mkdirSync(outDir, { recursive: true })
  writeFileSync(join(outDir, 'theme.css'), css)
  console.log('✅ Tailwind v4 theme generated!')
}

generate()